### ISSUE TITLE
[BUG] routes-segments-snake-case

### ISSUE THREAD

**Issue by Exelord** [netguru/eslint-plugin-ember#84]
Hi guys,
during running eslint with your plugin I'm getting this error.
The temporary fix for that is disabling the rule but I would like to use it if possible :)

```sh
Cannot read property 'map' of null
TypeError: Cannot read property 'map' of null
    at getSegmentNames (/Users/maciej/.nvm/versions/node/v7.9.0/lib/node_modules/eslint-plugin-ember/lib/rules/routes-segments-snake-case.js:32:9)
    at CallExpression.routeOptions.properties.forEach (/Users/maciej/.nvm/versions/node/v7.9.0/lib/node_modules/eslint-plugin-ember/lib/rules/routes-segments-snake-case.js:48:34)
    at Array.forEach (native)
    at Linter.CallExpression (/Users/maciej/.nvm/versions/node/v7.9.0/lib/node_modules/eslint-plugin-ember/lib/rules/routes-segments-snake-case.js:47:35)
    at emitOne (events.js:101:20)
    at Linter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/Users/maciej/.nvm/versions/node/v7.9.0/lib/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/maciej/.nvm/versions/node/v7.9.0/lib/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/Users/maciej/.nvm/versions/node/v7.9.0/lib/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/Users/maciej/.nvm/versions/node/v7.9.0/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at Traverser.enter (/Users/maciej/.nvm/versions/node/v7.9.0/lib/node_modules/eslint/lib/linter.js:922:36)
```

**Comment by michalsnik** [comment]
Hey @Exelord, thanks reporting an issue, but please paste the code example that is causing this as well, that would be really helpful :)

**Comment by Exelord** [comment]
This can be a problem because this project is a huge one and I'm not authorized to share even parts of this code. I will try to find the bug but I can't promise it will be possible :/

**Comment by Exelord** [comment]
OK, I know this is incorrect but for some reason, it is in use 🚑 .
You can try to write a test in case someone will put sth like this:

```js
  this.route('404', {
    path: '*:'
  });
```

**Comment by michalsnik** [comment]
Ok, I'll try to investigate it.

**Comment by Exelord** [comment]
@michalsnik The issue back to the life again :/

**Comment by michalsnik** [comment]
@Exelord in 4.3.0?

**Comment by Exelord** [comment]
Sorry for bothering. Works perfectly. I had old version in global scope :/

**Comment by michalsnik** [comment]
np, I'm glad it works :)
